### ISSUE TITLE
Submit User Login

### ISSUE THREAD

**Issue by thunder033** [The-Lounge/TheLounge#13]
Users should be able to authenticate through the UI
- login view access at `/#/login`
- users should use their RIT username to login
- password authentication later after usage of SSO is determined
- redirected to the home page
- if a user is already authenticated, navigating to the login automatically redirects to home

**Comment by caseymazza** [comment]
the categories page more or less is the home page, if we have something different, what would it look like and what kind of information would we have on it? unless home page is the person's page? although that wouldn't quite work for new people without an account.

**Comment by tlr3552** [comment]
Build failed, then was fixed and finally successful in [](https://circleci.com/gh/The-Lounge/TheLounge/14?utm_campaign=chatroom-integration&utm_medium=referral&utm_source=slack)
