### ISSUE TITLE
Auto Reconnect

### ISSUE THREAD

**Issue by JDevlieghere** [The-Lounge/TheLounge#72]
I love the red bar at the bottom of the screen that allows me to instantly reconnect when the connection is lost. This happens quite often to me, especially on my laptop. Could we reuse this logic to periodically check whether the connection is available again and when that is the case reconnect automatically?

**Comment by tlr3552** [comment]
To which line of code or file are you referring? I 'm not sure what you're referring to. That does sound like a neat feature to add at some point.

**Comment by JDevlieghere** [comment]
Oh man, this is a little embarrassing... I meant to open this issue in thelounge/lounge (the IRC client). Clearly I wasn't paying attention, I looked at the issues and saw some web socket stuff so I just assumed I had the right repo.
